package org.socraticgrid.wexcleanup.freebase.dao;
// Generated Nov 6, 2010 5:46:30 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Articles generated by hbm2java
 */
public class Articles  implements java.io.Serializable {


     private int wpid;
     private String name;
     private Date updated;
     private String xml;
     private String text;

    public Articles() {
    }

	
    public Articles(int wpid, String name, Date updated) {
        this.wpid = wpid;
        this.name = name;
        this.updated = updated;
    }
    public Articles(int wpid, String name, Date updated, String xml, String text) {
       this.wpid = wpid;
       this.name = name;
       this.updated = updated;
       this.xml = xml;
       this.text = text;
    }
   
    public int getWpid() {
        return this.wpid;
    }
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getXml() {
        return this.xml;
    }
    
    public void setXml(String xml) {
        this.xml = xml;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


