package org.socraticgrid.wexcleanup.freebase.dao;
// Generated Aug 9, 2010 4:30:55 PM by Hibernate Tools 3.2.1.GA



/**
 * CategoryMembers generated by hbm2java
 */
public class CategoryMembers  implements java.io.Serializable {


     private CategoryMembersId id;

    public CategoryMembers() {
    }

    public CategoryMembers(CategoryMembersId id) {
       this.id = id;
    }
   
    public CategoryMembersId getId() {
        return this.id;
    }
    
    public void setId(CategoryMembersId id) {
        this.id = id;
    }




}


