package org.socraticgrid.wexcleanup.freebase.dao;
// Generated Nov 6, 2010 5:46:30 PM by Hibernate Tools 3.2.1.GA



/**
 * FreebaseTypes generated by hbm2java
 */
public class FreebaseTypes  implements java.io.Serializable {


     private FreebaseTypesId id;

    public FreebaseTypes() {
    }

    public FreebaseTypes(FreebaseTypesId id) {
       this.id = id;
    }
   
    public FreebaseTypesId getId() {
        return this.id;
    }
    
    public void setId(FreebaseTypesId id) {
        this.id = id;
    }




}


