package org.socraticgrid.wexcleanup.freebase.dao;
// Generated Nov 6, 2010 5:46:30 PM by Hibernate Tools 3.2.1.GA



/**
 * FreebaseWpid generated by hbm2java
 */
public class FreebaseWpid  implements java.io.Serializable {


     private long id;
     private String guid;
     private int wpid;

    public FreebaseWpid() {
    }

    public FreebaseWpid(long id, String guid, int wpid) {
       this.id = id;
       this.guid = guid;
       this.wpid = wpid;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }
    public int getWpid() {
        return this.wpid;
    }
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }




}


