package org.socraticgrid.wexcleanup.freebase.dao;
// Generated Oct 1, 2010 11:36:24 AM by Hibernate Tools 3.2.1.GA



/**
 * FreebaseTypesId generated by hbm2java
 */
public class FreebaseTypesId  implements java.io.Serializable {


     private String guid;
     private String type;

    public FreebaseTypesId() {
    }

    public FreebaseTypesId(String guid, String type) {
       this.guid = guid;
       this.type = type;
    }
   
    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FreebaseTypesId) ) return false;
		 FreebaseTypesId castOther = ( FreebaseTypesId ) other; 
         
		 return ( (this.getGuid()==castOther.getGuid()) || ( this.getGuid()!=null && castOther.getGuid()!=null && this.getGuid().equals(castOther.getGuid()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGuid() == null ? 0 : this.getGuid().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         return result;
   }   


}


