package org.socraticgrid.wexcleanup.freebase.dao;
// Generated Sep 24, 2010 3:38:56 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FreebaseWpidId generated by hbm2java
 */
@Embeddable
public class FreebaseWpidId  implements java.io.Serializable {


     private String guid;
     private int wpid;

    public FreebaseWpidId() {
    }

    public FreebaseWpidId(String guid, int wpid) {
       this.guid = guid;
       this.wpid = wpid;
    }
   

    @Column(name="guid", nullable=false, length=32)
    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }

    @Column(name="wpid", nullable=false)
    public int getWpid() {
        return this.wpid;
    }
   
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FreebaseWpidId) ) return false;
		 FreebaseWpidId castOther = ( FreebaseWpidId ) other; 
         
		 return ( (this.getGuid()==castOther.getGuid()) || ( this.getGuid()!=null && castOther.getGuid()!=null && this.getGuid().equals(castOther.getGuid()) ) )
 && (this.getWpid()==castOther.getWpid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGuid() == null ? 0 : this.getGuid().hashCode() );
         result = 37 * result + this.getWpid();
         return result;
   }   


}


