package org.socraticgrid.wexcleanup.freebase.dao;
// Generated Nov 6, 2010 5:46:30 PM by Hibernate Tools 3.2.1.GA



/**
 * TemplateCalls generated by hbm2java
 */
public class TemplateCalls  implements java.io.Serializable {


     private long id;
     private int articleWpid;
     private Long sectionId;
     private String templateArticleName;

    public TemplateCalls() {
    }

	
    public TemplateCalls(long id, int articleWpid, String templateArticleName) {
        this.id = id;
        this.articleWpid = articleWpid;
        this.templateArticleName = templateArticleName;
    }
    public TemplateCalls(long id, int articleWpid, Long sectionId, String templateArticleName) {
       this.id = id;
       this.articleWpid = articleWpid;
       this.sectionId = sectionId;
       this.templateArticleName = templateArticleName;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public int getArticleWpid() {
        return this.articleWpid;
    }
    
    public void setArticleWpid(int articleWpid) {
        this.articleWpid = articleWpid;
    }
    public Long getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }
    public String getTemplateArticleName() {
        return this.templateArticleName;
    }
    
    public void setTemplateArticleName(String templateArticleName) {
        this.templateArticleName = templateArticleName;
    }




}


