
package org.medsphere.util.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AuthenticationService", targetNamespace = "http://service.util.medsphere.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.medsphere.util.service.UserInfo
     */
    @WebMethod(operationName = "ValidateAuthenticationInformation", action = "ValidateAuthenticationInformation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ValidateAuthenticationInformation", targetNamespace = "http://service.util.medsphere.org/", className = "org.medsphere.util.service.ValidateAuthenticationInformation")
    @ResponseWrapper(localName = "ValidateAuthenticationInformationResponse", targetNamespace = "http://service.util.medsphere.org/", className = "org.medsphere.util.service.ValidateAuthenticationInformationResponse")
    public UserInfo validateAuthenticationInformation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
