package gov.hhs.fha.nhinc.account.model;
// Generated May 11, 2011 1:15:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserSession generated by hbm2java
 */
public class UserSession  implements java.io.Serializable {
     private String token;
     private String userId;
     private String providerId;
     private Date loginTime;
     private Date lastUpdateTime;



    public UserSession() {
    }

	
    public UserSession(String token) {
        this.token = token;
    }
    
    public UserSession(String token, String userId, String providerId, 
            Date loginTime, Date lastUpdateTime) {
       this.token = token;
       this.userId = userId;
       this.providerId = providerId;
       this.loginTime = loginTime;
       this.lastUpdateTime = lastUpdateTime;
    }
   
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}


