
package gov.hhs.fha.nhinc.kmr.knowledgemodule;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "KnowledgeModuleService", targetNamespace = "urn:gov:hhs:fha:nhinc:kmr:knowledgemodule", wsdlLocation = "http://nhindev04.asu.edu:8080/KnowledgeModuleService/KmrKnowledgeModule?wsdl")
public class KnowledgeModuleService
    extends Service
{

    private final static URL KNOWLEDGEMODULESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gov.hhs.fha.nhinc.kmr.knowledgemodule.KnowledgeModuleService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gov.hhs.fha.nhinc.kmr.knowledgemodule.KnowledgeModuleService.class.getResource(".");
            url = new URL(baseUrl, "http://nhindev04.asu.edu:8080/KnowledgeModuleService/KmrKnowledgeModule?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://nhindev04.asu.edu:8080/KnowledgeModuleService/KmrKnowledgeModule?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        KNOWLEDGEMODULESERVICE_WSDL_LOCATION = url;
    }

    public KnowledgeModuleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KnowledgeModuleService() {
        super(KNOWLEDGEMODULESERVICE_WSDL_LOCATION, new QName("urn:gov:hhs:fha:nhinc:kmr:knowledgemodule", "KnowledgeModuleService"));
    }

    /**
     * 
     * @return
     *     returns KnowledgeModulePortType
     */
    @WebEndpoint(name = "KnowledgeModulePort")
    public KnowledgeModulePortType getKnowledgeModulePort() {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:kmr:knowledgemodule", "KnowledgeModulePort"), KnowledgeModulePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KnowledgeModulePortType
     */
    @WebEndpoint(name = "KnowledgeModulePort")
    public KnowledgeModulePortType getKnowledgeModulePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:gov:hhs:fha:nhinc:kmr:knowledgemodule", "KnowledgeModulePort"), KnowledgeModulePortType.class, features);
    }

}
