package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcsArticles generated by hbm2java
 */
@Entity
@Table(name="ecs_articles"
    ,schema="public"
)
public class EcsArticles  implements java.io.Serializable {


     private int wpid;
     private String name;
     private Date updated;
     private Serializable xml;
     private String text;

    public EcsArticles() {
    }

	
    public EcsArticles(int wpid, String name, Date updated) {
        this.wpid = wpid;
        this.name = name;
        this.updated = updated;
    }
    public EcsArticles(int wpid, String name, Date updated, Serializable xml, String text) {
       this.wpid = wpid;
       this.name = name;
       this.updated = updated;
       this.xml = xml;
       this.text = text;
    }
   
     @Id 
    
    @Column(name="wpid", unique=true, nullable=false)
    public int getWpid() {
        return this.wpid;
    }
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    
    @Column(name="xml")
    public Serializable getXml() {
        return this.xml;
    }
    
    public void setXml(Serializable xml) {
        this.xml = xml;
    }
    
    @Column(name="text")
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


