package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EcsCanidateWpids generated by hbm2java
 */
@Entity
@Table(name="ecs_canidate_wpids"
    ,schema="public"
)
public class EcsCanidateWpids  implements java.io.Serializable {


     private int id;
     private String guid;
     private int wpid;

    public EcsCanidateWpids() {
    }

    public EcsCanidateWpids(int id, String guid, int wpid) {
       this.id = id;
       this.guid = guid;
       this.wpid = wpid;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="guid", nullable=false, length=32)
    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }
    
    @Column(name="wpid", nullable=false)
    public int getWpid() {
        return this.wpid;
    }
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }




}


