package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EcsCandidateGuid generated by hbm2java
 */
@Entity
@Table(name="ecs_candidate_guid"
    ,schema="public"
)
public class EcsCandidateGuid  implements java.io.Serializable {


     private String id;
     private String name;
     private String source;

    public EcsCandidateGuid() {
    }

    public EcsCandidateGuid(String id, String name, String source) {
       this.id = id;
       this.name = name;
       this.source = source;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="source", nullable=false)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }




}


