package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EcsIcd9Wpids generated by hbm2java
 */
@Entity
@Table(name="ecs_icd9_wpids"
    ,schema="public"
)
public class EcsIcd9Wpids  implements java.io.Serializable {


     private int id;
     private String code;
     private int wpid;

    public EcsIcd9Wpids() {
    }

    public EcsIcd9Wpids(int id, String code, int wpid) {
       this.id = id;
       this.code = code;
       this.wpid = wpid;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="code", nullable=false)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="wpid", nullable=false)
    public int getWpid() {
        return this.wpid;
    }
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }




}


