package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FreebaseWpid generated by hbm2java
 */
@Entity
@Table(name="freebase_wpid"
    ,schema="public"
)
public class FreebaseWpid  implements java.io.Serializable {


     private FreebaseWpidId id;

    public FreebaseWpid() {
    }

    public FreebaseWpid(FreebaseWpidId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="guid", column=@Column(name="guid", nullable=false, length=32) ), 
        @AttributeOverride(name="wpid", column=@Column(name="wpid", nullable=false) ) } )
    public FreebaseWpidId getId() {
        return this.id;
    }
    
    public void setId(FreebaseWpidId id) {
        this.id = id;
    }




}


