package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FreebaseMedIcd9 generated by hbm2java
 */
@Entity
@Table(name="freebase_med_icd_9"
    ,schema="public"
)
public class FreebaseMedIcd9  implements java.io.Serializable {


     private String id;
     private String name;
     private String code;
     private String includesClassifications;
     private String parentClassification;

    public FreebaseMedIcd9() {
    }

    public FreebaseMedIcd9(String id, String name, String code, String includesClassifications, String parentClassification) {
       this.id = id;
       this.name = name;
       this.code = code;
       this.includesClassifications = includesClassifications;
       this.parentClassification = parentClassification;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="code", nullable=false)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="includes_classifications", nullable=false)
    public String getIncludesClassifications() {
        return this.includesClassifications;
    }
    
    public void setIncludesClassifications(String includesClassifications) {
        this.includesClassifications = includesClassifications;
    }
    
    @Column(name="parent_classification", nullable=false)
    public String getParentClassification() {
        return this.parentClassification;
    }
    
    public void setParentClassification(String parentClassification) {
        this.parentClassification = parentClassification;
    }




}


