package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FreebaseTypes generated by hbm2java
 */
@Entity
@Table(name="freebase_types"
    ,schema="public"
)
public class FreebaseTypes  implements java.io.Serializable {


     private FreebaseTypesId id;

    public FreebaseTypes() {
    }

    public FreebaseTypes(FreebaseTypesId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="guid", column=@Column(name="guid", nullable=false, length=32) ), 
        @AttributeOverride(name="type", column=@Column(name="type", nullable=false) ) } )
    public FreebaseTypesId getId() {
        return this.id;
    }
    
    public void setId(FreebaseTypesId id) {
        this.id = id;
    }




}


