package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Redirects generated by hbm2java
 */
@Entity
@Table(name="redirects"
    ,schema="public"
)
public class Redirects  implements java.io.Serializable {


     private int wpid;
     private String name;
     private String redirectsTo;

    public Redirects() {
    }

	
    public Redirects(int wpid, String name) {
        this.wpid = wpid;
        this.name = name;
    }
    public Redirects(int wpid, String name, String redirectsTo) {
       this.wpid = wpid;
       this.name = name;
       this.redirectsTo = redirectsTo;
    }
   
     @Id 
    
    @Column(name="wpid", unique=true, nullable=false)
    public int getWpid() {
        return this.wpid;
    }
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="redirects_to")
    public String getRedirectsTo() {
        return this.redirectsTo;
    }
    
    public void setRedirectsTo(String redirectsTo) {
        this.redirectsTo = redirectsTo;
    }




}


