package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TemplateCalls generated by hbm2java
 */
@Entity
@Table(name="template_calls"
    ,schema="public"
)
public class TemplateCalls  implements java.io.Serializable {


     private long id;
     private int articleWpid;
     private Long sectionId;
     private String templateArticleName;

    public TemplateCalls() {
    }

	
    public TemplateCalls(long id, int articleWpid, String templateArticleName) {
        this.id = id;
        this.articleWpid = articleWpid;
        this.templateArticleName = templateArticleName;
    }
    public TemplateCalls(long id, int articleWpid, Long sectionId, String templateArticleName) {
       this.id = id;
       this.articleWpid = articleWpid;
       this.sectionId = sectionId;
       this.templateArticleName = templateArticleName;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="article_wpid", nullable=false)
    public int getArticleWpid() {
        return this.articleWpid;
    }
    
    public void setArticleWpid(int articleWpid) {
        this.articleWpid = articleWpid;
    }
    
    @Column(name="section_id")
    public Long getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }
    
    @Column(name="template_article_name", nullable=false)
    public String getTemplateArticleName() {
        return this.templateArticleName;
    }
    
    public void setTemplateArticleName(String templateArticleName) {
        this.templateArticleName = templateArticleName;
    }




}


