package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TemplateValuesId generated by hbm2java
 */
@Embeddable
public class TemplateValuesId  implements java.io.Serializable {


     private long callId;
     private String name;

    public TemplateValuesId() {
    }

    public TemplateValuesId(long callId, String name) {
       this.callId = callId;
       this.name = name;
    }
   

    @Column(name="call_id", nullable=false)
    public long getCallId() {
        return this.callId;
    }
    
    public void setCallId(long callId) {
        this.callId = callId;
    }

    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TemplateValuesId) ) return false;
		 TemplateValuesId castOther = ( TemplateValuesId ) other; 
         
		 return (this.getCallId()==castOther.getCallId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCallId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   


}


