package org.socraticgrid.icd9wikiextractor.freebase.dao;
// Generated Sep 23, 2010 3:53:17 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TemplateValues generated by hbm2java
 */
@Entity
@Table(name="template_values"
    ,schema="public"
)
public class TemplateValues  implements java.io.Serializable {


     private TemplateValuesId id;
     private Serializable xml;

    public TemplateValues() {
    }

	
    public TemplateValues(TemplateValuesId id) {
        this.id = id;
    }
    public TemplateValues(TemplateValuesId id, Serializable xml) {
       this.id = id;
       this.xml = xml;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="callId", column=@Column(name="call_id", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="name", nullable=false) ) } )
    public TemplateValuesId getId() {
        return this.id;
    }
    
    public void setId(TemplateValuesId id) {
        this.id = id;
    }
    
    @Column(name="xml")
    public Serializable getXml() {
        return this.xml;
    }
    
    public void setXml(Serializable xml) {
        this.xml = xml;
    }




}


