
package gov.hhs.fha.nhinc.adapter.commondatalayer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.hl7.v3.ActReferencePOORIN200911UVMessageType;
import org.hl7.v3.CareRecordQUPCIN040100UV01RequestType;
import org.hl7.v3.CareRecordQUPCIN040200UV01MessageType;
import org.hl7.v3.CareRecordQUPCIN043100UV01RequestType;
import org.hl7.v3.CareRecordQUPCIN043200UV01MessageType;
import org.hl7.v3.CompositeOrderPOORIN200901UVRequestType;
import org.hl7.v3.FindEncountersPRPAIN900300UV02RequestType;
import org.hl7.v3.FindEncountersPRPAIN900350UV02MessageType;
import org.hl7.v3.FindPatientsPRPAIN201305UVRequestType;
import org.hl7.v3.FindPatientsPRPAMT201310UVResponseType;
import org.hl7.v3.ObjectFactory;
import org.hl7.v3.PatientDemographicsPRPAIN201307UV02RequestType;
import org.hl7.v3.PatientDemographicsPRPAMT201303UVResponseType;
import org.hl7.v3.ProviderDetailsPRPMIN306010UV1RequestType;
import org.hl7.v3.ProviderDetailsPRPMIN306011UV01ResponseType;
import org.hl7.v3.ResultEventPOLBIN364000UV01MessageType;
import org.hl7.v3.ResultQueryPOLBIN354000UV01MessageType;
import org.hl7.v3.SlotRequestPRSCIN030101UVMessageType;
import org.hl7.v3.SlotResponseMessageType;
import org.hl7.v3.SlotsQueryResponsePRSCIN030102UVMessageType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CommonDataLayerPortType", targetNamespace = "urn:gov:hhs:fha:nhinc:adapter:commondatalayer")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonDataLayerPortType {


    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.FindEncountersPRPAIN900350UV02MessageType
     */
    @WebMethod(operationName = "FindEncounters", action = "urn:FindEncounters")
    @WebResult(name = "FindEncounters_PRPA_IN900350UV02Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public FindEncountersPRPAIN900350UV02MessageType findEncounters(
        @WebParam(name = "FindEncounters_PRPA_IN900300UV02Request", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        FindEncountersPRPAIN900300UV02RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetProcedures", action = "urn:Procedures")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getProcedures(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01ProceduresRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetMedications", action = "urn:Medications")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getMedications(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01MedicationsRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetAllergies", action = "urn:Allergies")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getAllergies(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01AllergiesRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetVitals", action = "urn:Vitals")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getVitals(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01VitalsRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetProblems", action = "urn:Problems")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getProblems(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01ProblemsRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetTestResults", action = "urn:TestResults")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getTestResults(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01TestResultsRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetImagingResults", action = "urn:ImagingResults")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getImagingResults(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01ImagingResultsRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetImmunizations", action = "urn:Immunizations")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getImmunizations(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01ImmunizationsRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetFamilyHistory", action = "urn:FamilyHistory")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getFamilyHistory(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01FamilyHistoryRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetSocialHistory", action = "urn:SocialHistory")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getSocialHistory(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01SocialHistoryRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetInsurances", action = "urn:Insurances")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getInsurances(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01Request", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN043200UV01MessageType
     */
    @WebMethod(operationName = "GetOrders", action = "urn:Orders")
    @WebResult(name = "CareRecord_QUPC_IN043200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN043200UV01MessageType getOrders(
        @WebParam(name = "CareRecord_QUPC_IN043100UV01OrdersRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN043100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.PatientDemographicsPRPAMT201303UVResponseType
     */
    @WebMethod(operationName = "GetPatienInfo", action = "urn:GetPatienInfo")
    @WebResult(name = "PatientDemographics_PRPA_MT201303UVResponse", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public PatientDemographicsPRPAMT201303UVResponseType getPatienInfo(
        @WebParam(name = "PatientDemographics_PRPA_IN201307UV02Request", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        PatientDemographicsPRPAIN201307UV02RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.FindPatientsPRPAMT201310UVResponseType
     */
    @WebMethod(operationName = "FindPatients", action = "urn:FindPatients")
    @WebResult(name = "FindPatients_PRPA_MT201310UVResponse", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public FindPatientsPRPAMT201310UVResponseType findPatients(
        @WebParam(name = "FindPatients_PRPA_IN201305UVRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        FindPatientsPRPAIN201305UVRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.ProviderDetailsPRPMIN306011UV01ResponseType
     */
    @WebMethod(operationName = "FindProviders", action = "urn:FindProviders")
    @WebResult(name = "ProviderDetails_PRPM_IN306011UV01Response", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public ProviderDetailsPRPMIN306011UV01ResponseType findProviders(
        @WebParam(name = "ProviderDetails_PRPM_IN306010UV1Request", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        ProviderDetailsPRPMIN306010UV1RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.SlotResponseMessageType
     */
    @WebMethod(operationName = "AppointmentSlotRequest", action = "urn:AppointmentSlotRequest")
    @WebResult(name = "SlotResponse_Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public SlotResponseMessageType appointmentSlotRequest(
        @WebParam(name = "SlotRequest_PRSC_IN030101UVMessage", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        SlotRequestPRSCIN030101UVMessageType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.ResultEventPOLBIN364000UV01MessageType
     */
    @WebMethod(operationName = "FindResultEventQuery", action = "urn:FindResultEventQuery")
    @WebResult(name = "ResultEvent_POLB_IN364000UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public ResultEventPOLBIN364000UV01MessageType findResultEventQuery(
        @WebParam(name = "ResultQuery_POLB_IN354000UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        ResultQueryPOLBIN354000UV01MessageType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.ActReferencePOORIN200911UVMessageType
     */
    @WebMethod(operationName = "LabOrderRequest", action = "urn:LabOrderRequest")
    @WebResult(name = "ActReference_POOR_IN200911UVMessage", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public ActReferencePOORIN200911UVMessageType labOrderRequest(
        @WebParam(name = "CompositeOrder_POOR_IN200901UVLabRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CompositeOrderPOORIN200901UVRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN040200UV01MessageType
     */
    @WebMethod(operationName = "GetAmbEncounterDetails", action = "urn:GetAmbEncounterDetails")
    @WebResult(name = "CareRecord_QUPC_IN040200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN040200UV01MessageType getAmbEncounterDetails(
        @WebParam(name = "AMBCareRecord_QUPC_IN040100UV01Request", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN040100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.CareRecordQUPCIN040200UV01MessageType
     */
    @WebMethod(operationName = "GetImpEncounterDetails", action = "urn:GetImpEncounterDetails")
    @WebResult(name = "CareRecord_QUPC_IN040200UV01Message", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public CareRecordQUPCIN040200UV01MessageType getImpEncounterDetails(
        @WebParam(name = "IMPCareRecord_QUPC_IN040100UV01Request", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        CareRecordQUPCIN040100UV01RequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.hl7.v3.SlotsQueryResponsePRSCIN030102UVMessageType
     */
    @WebMethod(operationName = "FindSlots", action = "urn:FindSlots")
    @WebResult(name = "SlotsQueryResponse_PRSC_IN030102UVMessage", targetNamespace = "urn:hl7-org:v3", partName = "output")
    public SlotsQueryResponsePRSCIN030102UVMessageType findSlots(
        @WebParam(name = "SlotsQuery_PRSC_IN030101UVRequest", targetNamespace = "urn:hl7-org:v3", partName = "param0")
        SlotRequestPRSCIN030101UVMessageType param0);

}
