package org.socraticgrid.ecs.hibernate.dao;
// Generated Nov 21, 2011 5:16:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EcsAltArticles generated by hbm2java
 */
public class EcsAltArticles  implements java.io.Serializable {


     private int wpid;
     private String name;
     private Date updated;
     private String xml;
     private String text;
     private Integer readinglevel;
     private String language;

    public EcsAltArticles() {
    }

	
    public EcsAltArticles(int wpid, String name, Date updated) {
        this.wpid = wpid;
        this.name = name;
        this.updated = updated;
    }
    public EcsAltArticles(int wpid, String name, Date updated, String xml, String text, Integer readinglevel, String language) {
       this.wpid = wpid;
       this.name = name;
       this.updated = updated;
       this.xml = xml;
       this.text = text;
       this.readinglevel = readinglevel;
       this.language = language;
    }
   
    public int getWpid() {
        return this.wpid;
    }
    
    public void setWpid(int wpid) {
        this.wpid = wpid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getXml() {
        return this.xml;
    }
    
    public void setXml(String xml) {
        this.xml = xml;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Integer getReadinglevel() {
        return this.readinglevel;
    }
    
    public void setReadinglevel(Integer readinglevel) {
        this.readinglevel = readinglevel;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }




}


