package org.socraticgrid.ecs.hibernate.dao;
// Generated Nov 21, 2011 5:16:07 PM by Hibernate Tools 3.2.1.GA



/**
 * EcsCandidateGuid generated by hbm2java
 */
public class EcsCandidateGuid  implements java.io.Serializable {


     private int id;
     private String guid;
     private String name;
     private String source;
     private String scheme;

    public EcsCandidateGuid() {
    }

    public EcsCandidateGuid(int id, String guid, String name, String source, String scheme) {
       this.id = id;
       this.guid = guid;
       this.name = name;
       this.source = source;
       this.scheme = scheme;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getScheme() {
        return this.scheme;
    }
    
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }




}


