package org.socraticgrid.ecs.hibernate.dao;
// Generated Nov 21, 2011 5:16:07 PM by Hibernate Tools 3.2.1.GA



/**
 * EcsSchemeAlias generated by hbm2java
 */
public class EcsSchemeAlias  implements java.io.Serializable {


     private long id;
     private String alias;
     private String scheme;
     private Boolean canonical;
     private Boolean name;

    public EcsSchemeAlias() {
    }

	
    public EcsSchemeAlias(long id, String alias, String scheme) {
        this.id = id;
        this.alias = alias;
        this.scheme = scheme;
    }
    public EcsSchemeAlias(long id, String alias, String scheme, Boolean canonical, Boolean name) {
       this.id = id;
       this.alias = alias;
       this.scheme = scheme;
       this.canonical = canonical;
       this.name = name;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getScheme() {
        return this.scheme;
    }
    
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }
    public Boolean getCanonical() {
        return this.canonical;
    }
    
    public void setCanonical(Boolean canonical) {
        this.canonical = canonical;
    }

    public Boolean getName() {
        return this.name;
    }

    public void setName(Boolean canonical) {
        this.name = canonical;
    }



}


