package org.socraticgrid.ecs.hibernate.dao;
// Generated Nov 21, 2011 5:16:07 PM by Hibernate Tools 3.2.1.GA



/**
 * EcsSectionAlias generated by hbm2java
 */
public class EcsSectionAlias  implements java.io.Serializable {


     private long id;
     private String scheme;
     private String section;
     private String alias;
     private Character language;

    public EcsSectionAlias() {
    }

	
    public EcsSectionAlias(long id) {
        this.id = id;
    }
    public EcsSectionAlias(long id, String scheme, String section, String alias, Character language) {
       this.id = id;
       this.scheme = scheme;
       this.section = section;
       this.alias = alias;
       this.language = language;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getScheme() {
        return this.scheme;
    }
    
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public Character getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Character language) {
        this.language = language;
    }




}


