package org.socraticgrid.ecs.hibernate.dao;
// Generated Nov 21, 2011 5:16:07 PM by Hibernate Tools 3.2.1.GA



/**
 * EcsSectionData generated by hbm2java
 */
public class EcsSectionData  implements java.io.Serializable {


     private long id;
     private String scheme;
     private String code;
     private String section;
     private String xml;
     private String language;
     private String readinglevel;
     private String source;

    public EcsSectionData() {
    }

	
    public EcsSectionData(long id, String scheme, String code, String section) {
        this.id = id;
        this.scheme = scheme;
        this.code = code;
        this.section = section;
    }
    public EcsSectionData(long id, String scheme, String code, String section, String xml, String language, String readinglevel, String source) {
       this.id = id;
       this.scheme = scheme;
       this.code = code;
       this.section = section;
       this.xml = xml;
       this.language = language;
       this.readinglevel = readinglevel;
       this.source = source;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getScheme() {
        return this.scheme;
    }
    
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getXml() {
        return this.xml;
    }
    
    public void setXml(String xml) {
        this.xml = xml;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getReadinglevel() {
        return this.readinglevel;
    }
    
    public void setReadinglevel(String readinglevel) {
        this.readinglevel = readinglevel;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }



}


